name: Wails build

on:
  push:
    tags:
      - '*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"
  APPNAME: copilot-activator

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - os: 'ubuntu-latest'
          - os: 'windows-latest'
          - os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup GoLang
        uses: actions/setup-go@v4
        with:
          check-latest: true
          go-version: ^1.18
      - run: go version
          
      # install wails
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
        shell: bash
        
      - name: Linux Dependencies
        if: runner.os == 'Linux'
        working-directory: ${{ github.workspace }}
        run: |
          sudo apt-get update && sudo apt-get install libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu

      - name: Build Linux x64
        if: runner.os == 'Linux'
        working-directory: ${{ github.workspace }}
        run: |
          wails build -s --platform linux/amd64 -o $APPNAME
          cd ${{ github.workspace }}/build/bin
          zip -r $APPNAME-linux-x64.zip $APPNAME
          rm $APPNAME

      - name: Build Windows x64
        if: runner.os == 'Windows'
        working-directory: ${{ github.workspace }}
        run: |
          wails build -s --platform windows/amd64 -o $Env:APPNAME".exe"
          cd ${{ github.workspace }}\build\bin
          powershell Compress-Archive -Path $Env:APPNAME".exe" -DestinationPath $Env:APPNAME-windows-x64.zip
          del $Env:APPNAME".exe"

      - name: macOS Dependencies
        if: runner.os == 'macOS'
        working-directory: ${{ github.workspace }}
        run: |
          brew install mitchellh/gon/gon
          
      - name: Build macOS x64
        if: runner.os == 'macOS'
        working-directory: ${{ github.workspace }}
        run: |
          wails build -s --platform darwin/amd64 -o $APPNAME
          cd ${{ github.workspace }}/build/bin
          ditto -c -k $APPNAME.app $APPNAME-macos-x64.zip
          rm -rf $APPNAME.app

      - uses: actions/upload-artifact@v3
        with:
          name: Wails Build ${{runner.os}}
          path: |
            */bin/
            *\bin\*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            */bin/*